on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Deployment ${{ job.status }}"
          to: team@example.com
          from: GitHub Actions
          body: |
            Deployment status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}